# Generated by Django 6.0.4 on 2026-04-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_wishlist_alter_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='course',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
