# Generated by Django 6.0.4 on 2026-04-28 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_course_customer_middle_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_delivery_staff',
            field=models.BooleanField(default=False),
        ),
    ]
