# Generated by Django 6.0.4 on 2026-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_cancel_message_order_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='room_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
