# Generated by Django 6.0.4 on 2026-04-28 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_is_delivery_staff'),
        ('orders', '0006_remove_order_product_remove_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_orders', to='customers.customer'),
        ),
    ]
