# Generated by Django 6.0.4 on 2026-04-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Notebooks', 'Notebooks'), ('Writing', 'Writing Instruments'), ('Bags', 'Bags & Backpacks'), ('Art', 'Art Supplies'), ('Other', 'Other')], max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Optional external image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
